---
title: "Why are people so excited about R?"
author: "Nathan Stephens"
date: "4/1/2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R

* Why do people love R?
* Our tools enable a data data scientists to take full advantage of the full power of R. 
* I’m going to show you in less than 2 min

## RStudio Toolchain

* The RStudio IDE
* A complete and total toolchain
* We know R

## Shiny applications

* Develop a Shiny app in the IDE
* One click publishing
* Easy!

## Benefits

* We eliminated a lot of work, right?
* And our work is completely reproducible
* Take advantage of the investments you’ve made in your R users

## Reports

* Develop in the IDE
* One click publishing
* Easy!

## API

* Develop in the IDE
* One click publishing
* Easy!

## TensorFlow

* Develop in the IDE
* One click publishing
* Easy!

## Databases

* Develop in the IDE
* One click publishing
* Easy!

## You getting this?

* Here is what you would have had to do!
* RStudio makes it easy for your people to take advantage of the full power of R

## RStudio

RStudio has a mission to provide the most widely used open source and enterprise-ready professional software for the R statistical computing environment. We offer open source and enterprise ready tools for the R computing environment.
